<?php

   $config['safe_forms']['reservations_form']=array('form_view_file'=>'plugins/svg/hotel_manager/view_make_reservation.php',
                                                    'php_validation'=>array('enabled'=>true,
                                                                            'php_errors'=>array('show_errors'=>false,
                                                                                                'mode'=>'all', // 'all' | 'individual'
                                                                                                'error_container_id'=>'errori_php_reservation_form')), // Nel caso di 'individual' gli id dei containers sono $name_ERROR_CONTAINER_ID
                                                    'js_validation'=>array('enabled'=>true,
                                                                           'field_classes_on_validation'=>array('successful'=>'input_ok',
                                                                                                                'failed'=>'input_error'),
                                                                           'submit_id'=>'send_reservation'),
                                                    'motion_captcha'=>array('enabled'=>false),
                                                    'autocomplete'=>false,
                                                    'char_counter'=>array('enable'=>true,
                                                                          'mode'=>'written_total',  // 'missing' indica solo il num di caratteri mancanti per raggiungere il max_length, 'written_total' indica il numero di caratteri immessi rispetto al totale nella forma X/Y
                                                                          'counter_div_class'=>'contatore_caratteri'),
                                                    'precompile_fields_after_submission'=>false,
                                                    'alert_submission_ok'=>array('enabled'=>true,
                                                                                 'auto_call'=>false,
                                                                                 'options'=>'{autoOpen:false, show:"blind", hide:"explode", width:500, title:"Conferma di avvenuto invio"}',
                                                                                 'message'=>'La richiesta di prenotazione è stata inoltrata correttamente.<br>Tra breve sarai contattato da un nostro Operatore.'),
                                                    'confirm_before_submission'=>array('enable'=>true,
                                                                                       'message'=>array('source_mode'=>'container_selector', // 'direct' | 'view' | 'container_selector' 
                                                                                                        'content'=>'#report'), // Il contenuto esplicito ('direct') o il file di view ('view') o il selettore jQuery di un container del DOM
                                                                                       'dialog_options'=>'{modal:true,width:700,title:"Riepilogo della Richiesta di Prenotazione"}'),
                                                    'inputs'=>array(
                                                                    'referente'=>array('label'=>'Nome del Referente',
                                                                                       'php_rules'=>'trim|required|min_length[5]|max_length[25]|xss_clean',
                                                                                       'js_rules'=>'required|minSize[5]|maxSize[25]',
                                                                                       'promptPosition'=>'topRight'),         
                                                                    'referente_telefono'=>array('label'=>'Telefono del Referente',
                                                                                                 'php_rules'=>'trim|required|min_length[5]|max_length[15]|xss_clean',
                                                                                                 'js_rules'=>'required|minSize[5]|maxSize[15]',
                                                                                                 'promptPosition'=>'topRight'),   
                                                                    'referente_email'=>array('label'=>'E-mail del Referente',
                                                                                             'php_rules'=>'trim|required|min_length[5]|max_length[25]|xss_clean',
                                                                                             'js_rules'=>'required|minSize[5]|maxSize[25]|custom[email]',
                                                                                             'promptPosition'=>'topRight:-80'),
                                                                    'referente_indirizzo'=>array('label'=>'Indirizzo del Referente',
                                                                                       'php_rules'=>'trim|min_length[5]|max_length[30]|xss_clean',
                                                                                       'js_rules'=>'minSize[5]|maxSize[30]',
                                                                                       'promptPosition'=>'bottomLeft'),         
                                                                    'referente_citta'=>array('label'=>'Città del Referente',
                                                                                                 'php_rules'=>'trim|min_length[2]|max_length[25]|xss_clean',
                                                                                                 'js_rules'=>'minSize[2]|maxSize[25]',
                                                                                                 'promptPosition'=>'bottomLeft'),   
                                                                    'referente_provincia'=>array('label'=>'Provincia del Referente',
                                                                                             'php_rules'=>'trim|min_length[2]|max_length[15]|xss_clean',
                                                                                             'js_rules'=>'minSize[2]|maxSize[15]',
                                                                                             'promptPosition'=>'bottomLeft'),                                                                                             
                                                                    'date_soggiorno_da'=>array('label'=>'Data inizio soggiorno',
                                                                                               'php_rules'=>'trim|required|exact_length[10]|callback_check_data[dd/mm/yyyy]|xss_clean',
                                                                                               'js_rules'=>'required',
                                                                                               'promptPosition'=>'topRight'),                      
                                                                    'date_soggiorno_a'=>array('label'=>'Data fine soggiorno',
                                                                                              'php_rules'=>'trim|required|exact_length[10]|callback_check_data[dd/mm/yyyy]|xss_clean',
                                                                                              'js_rules'=>'required',
                                                                                              'promptPosition'=>'topRight'),                      
                                                                    'num_ospiti'=>array('label'=>'Numero Ospiti',
                                                                                        'php_rules'=>'trim|required|is_natural_no_zero|xss_clean',
                                                                                        'js_rules'=>'required|custom[integer]|equals[totale_posti_letto_indicati]|min[1]',
                                                                                        'promptPosition'=>'bottomLeft:335'),                      
                                                                    'quadruple'=>array('label'=>'Quadruple',
                                                                                       'php_rules'=>'trim|required|is_natural|xss_clean',
                                                                                       'js_rules'=>'required|custom[integer]',
                                                                                       'promptPosition'=>'topRight'),                      
                                                                    'triple'=>array('label'=>'Triple',
                                                                                    'php_rules'=>'trim|required|is_natural|xss_clean',
                                                                                    'js_rules'=>'required|custom[integer]',
                                                                                    'promptPosition'=>'topRight'),                      
                                                                    'doppie'=>array('label'=>'Doppie',
                                                                                    'php_rules'=>'trim|required|is_natural|xss_clean',
                                                                                    'js_rules'=>'required|custom[integer]',
                                                                                    'promptPosition'=>'topRight'),                      
                                                                    'singole'=>array('label'=>'Singole',
                                                                                     'php_rules'=>'trim|required|is_natural|xss_clean',
                                                                                     'js_rules'=>'required|custom[integer]',
                                                                                     'promptPosition'=>'topRight:50'),
                                                                    'cena'=>array('label'=>'Cena',
                                                                                  'php_rules'=>'trim|required|xss_clean',
                                                                                  'js_rules'=>'required',
                                                                                  'promptPosition'=>'centerRight'),
                                                                    'note'=>array('label'=>'Note',
                                                                                  'php_rules'=>'trim|max_length[500]|xss_clean',
                                                                                  'js_rules'=>'maxSize[500]',
                                                                                  'promptPosition'=>'topRight:-140')));

   $config['safe_forms']['login_form']=array('form_view_file'=>'plugins/login/view_login.php',
                                             'php_validation'=>array('enabled'=>true,
                                                                     'php_errors'=>array('show_errors'=>true,
                                                                                         'mode'=>'individual', // 'all' | 'individual'
                                                                                         'error_container_id'=>'errori_php_login_form')), // Nel caso di 'individual' gli id dei containers sono $name_ERROR_CONTAINER_ID
                                             'js_validation'=>array('enabled'=>true,
                                                                    'field_classes_on_validation'=>array('successful'=>'input_ok',
                                                                                                         'failed'=>'input_error'),
                                                                    'submit_id'=>'login_enter'),
                                             'motion_captcha'=>array('enabled'=>true,
                                                                     'container_id'=>'captcha_login',
                                                                     'title'=>'<p>Disegna la forma che vedi nel box</p>',
                                                                     'error_msg'=>'La forma non corrisponde, riprovare...',
                                                                     'success_msg'=>'Ottimo, la forma corrisponde!'),
                                             'char_counter'=>array('enable'=>false,
                                                                   'mode'=>'written_total',  // 'missing' indica solo il num di caratteri mancanti per raggiungere il max_length, 'written_total' indica il numero di caratteri immessi rispetto al totale nella forma X/Y
                                                                   'counter_div_class'=>'contatore_caratteri'),
                                             'inputs'=>array('user_id'=>array('label'=>'User ID',
                                                                              'php_rules'=>'trim|required|min_length[6]|max_length[10]|xss_clean',
                                                                              'js_rules'=>'required|minSize[6]|maxSize[10]',
                                                                              'promptPosition'=>'topRight'),
                                                             'password_id_1'=>array('label'=>'Password',
                                                                                    'php_rules'=>'trim|required|min_length[6]|max_length[10]|xss_clean',
                                                                                    'js_rules'=>'required|minSize[6]|maxSize[10]',
                                                                                    'promptPosition'=>'bottomRight'),                      
                                                             'password_id_2'=>array('label'=>'Conferma Password',
                                                                                    'php_rules'=>'trim|required|min_length[6]|max_length[10]|xss_clean',
                                                                                    'js_rules'=>'required|minSize[6]|maxSize[10]',
                                                                                    'promptPosition'=>'bottomRight'),                      
                                                             'nome_login'=>array('label'=>'Nome',
                                                                                 'php_rules'=>'trim|required|min_length[6]|max_length[15]|xss_clean',
                                                                                 'js_rules'=>'required|minSize[6]|maxSize[15]',
                                                                                 'promptPosition'=>'centerRight:70'),                      
                                                             'cognome_login'=>array('label'=>'Conferma Password',
                                                                                    'php_rules'=>'trim|required|min_length[6]|max_length[15]|xss_clean',
                                                                                    'js_rules'=>'required|minSize[6]|maxSize[15]',
                                                                                    'promptPosition'=>'centerRight:70'),                      
                                                             'email_address_login'=>array('label'=>'Conferma Password',
                                                                                          'php_rules'=>'trim|required|valid_email|xss_clean',
                                                                                          'js_rules'=>'required|custom[email]',
                                                                                          'promptPosition'=>'centerRight:70')));
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    

   $config['safe_forms']['email_form_dialog']=array('form_view_file'=>'sito/elementi_comuni/view_email_form_dialog.php',
                                                    'php_validation'=>array('enabled'=>true,
                                                                            'php_errors'=>array('show_errors'=>true,
                                                                                                'mode'=>'all', // 'all' | 'individual'
                                                                                                'error_container_id'=>'errori_php_email_form_dialog')), // Nel caso di 'individual' gli id dei containers sono $name_ERROR_CONTAINER_ID   
                                                    'js_validation'=>array('enabled'=>true,
                                                                           'field_classes_on_validation'=>array('successful'=>'input_ok',
                                                                                                                'failed'=>'input_error'),
                                                                           'submit_id'=>''),
                                                    'motion_captcha'=>array('enabled'=>false),
                                                    'inputs'=>array('nome_cognome_dialog'=>array('label'=>'Nome e Cognome',
                                                                                                 'php_rules'=>'trim|required|min_length[6]|max_length[30]|xss_clean',
                                                                                                 'js_rules'=>'required|minSize[6]|maxSize[30]',
                                                                                                 'promptPosition'=>'bottomRight:10'),
                                                                    'indirizzo_email_dialog'=>array('label'=>'Indirizzo Email',
                                                                                                    'php_rules'=>'trim|required|valid_email|xss_clean',
                                                                                                    'js_rules'=>'required|custom[email]',
                                                                                                    'promptPosition'=>'bottomLeft:-10'),                      
                                                                    'messaggio_email_dialog'=>array('label'=>'Messaggio Email',
                                                                                                    'php_rules'=>'trim|required|max_length[200]|xss_clean',
                                                                                                    'js_rules'=>'required|maxSize[200]',
                                                                                                    'promptPosition'=>'topRight:-140')));

   $config['safe_forms']['email_form']=array('form_view_file'=>'plugins/email/view_email_form.php',
                                             'php_validation'=>array('enabled'=>true,
                                                                     'php_errors'=>array('show_errors'=>true,
                                                                                         'mode'=>'individual', // 'all' | 'individual'
                                                                                         'error_container_id'=>'errori_php_email_form')), // Nel caso di 'individual' gli id dei containers sono $name_ERROR_CONTAINER_ID   
                                             'js_validation'=>array('enabled'=>true,
                                                                    'field_classes_on_validation'=>array('successful'=>'input_ok',
                                                                                                         'failed'=>'input_error'),
                                                                    'submit_id'=>'email_send'),
                                             'motion_captcha'=>array('enabled'=>false),
                                             'char_counter'=>array('enable'=>false,
                                                                   'mode'=>'written_total',  // 'missing' indica solo il num di caratteri mancanti per raggiungere il max_length, 'written_total' indica il numero di caratteri immessi rispetto al totale nella forma X/Y
                                                                   'counter_div_class'=>'contatore_caratteri'),
                                             'inputs'=>array('nome_cognome'=>array('label'=>'Nome e Cognome',
                                                                                   'php_rules'=>'trim|required|min_length[6]|max_length[30]|xss_clean',
                                                                                   'js_rules'=>'required|minSize[6]|maxSize[30]',
                                                                                   'promptPosition'=>'topRight'),
                                                             'indirizzo_email'=>array('label'=>'Indirizzo Email',
                                                                                      'php_rules'=>'trim|required|valid_email|xss_clean',
                                                                                      'js_rules'=>'required|custom[email]|maxSize[50]',
                                                                                      'promptPosition'=>'bottomRight'),                      
                                                             'messaggio_email'=>array('label'=>'Messaggio Email',
                                                                                      'php_rules'=>'trim|required|max_length[500]|xss_clean',
                                                                                      'js_rules'=>'required|maxSize[500]',
                                                                                      'promptPosition'=>'topRight:-140')));


   $config['safe_forms']['mailing_list']=array('form_view_file'=>'sito/pagine/home/forms/form_mailing_list.php',
                                               'php_validation'=>array('enabled'=>true,
                                                                       'php_errors'=>array('show_errors'=>true,
                                                                                           'mode'=>'all', // 'all' | 'individual'
                                                                                           'error_container_id'=>'errori_php_mailing_list')), // Nel caso di 'individual' gli id dei containers sono $name_ERROR_CONTAINER_ID   
                                               'js_validation'=>array('enabled'=>true,
                                                                      'field_classes_on_validation'=>array('successful'=>'input_ok',
                                                                                                           'failed'=>'input_error'),
                                                                      'submit_id'=>'pulsante_newsletter'),
                                               'motion_captcha'=>array('enabled'=>false),
                                               'inputs'=>array('indirizzo_mailing_list'=>array('label'=>'Mailing list',
                                                                                               'php_rules'=>'trim|required|valid_email|xss_clean',
                                                                                               'js_rules'=>'required|custom[email]',
                                                                                               'promptPosition'=>'bottomLeft',
                                                                                               'db'=>array('db_enabled'=>true,
                                                                                                           'db_disable_if_some_other_validation_fails'=>true,
                                                                                                           'db_table'=>'mailing_list',
                                                                                                           'db_field'=>'email',
                                                                                                           'db_where'=>array(),
                                                                                                           'db_parsing_function'=>'parse_strtolower',
                                                                                                           'db_save_action'=>'insert_once'))));


/**************************************************************************************************************************************************/
/************************************************************* Non toccare qui sotto **************************************************************/
/**************************************************************************************************************************************************/

   $config['safe_forms']['headers'] = array('jquery.validationEngine-it.js'=>'application/libraries/librerie_JS/jquery_plugins/jquery_validation_engine_2.6.1/js/languages',
                                            'jquery.validationEngine.js'=>'application/libraries/librerie_JS/jquery_plugins/jquery_validation_engine_2.6.1/js',
                                            'validationEngine.jquery.css'=>'application/libraries/librerie_JS/jquery_plugins/jquery_validation_engine_2.6.1/css',
                                            'validazioni.less'=>'application/views/stili/plugins',
                                            'jquery.motionCaptcha.0.2.css'=>'application/libraries/librerie_JS/jquery_plugins/motion_captcha_0.2',
                                            'jquery.motionCaptcha.0.2.js'=>'application/libraries/librerie_JS/jquery_plugins/motion_captcha_0.2',
                                            'dialog.js'=>'application/JS/dialog'); 
   
?>