/* JS */ gapi.loaded_1(function(_){var window=this;
_.jg=2147483648*window.Math.random()|0;
_.kg=function(a){return a[_.pa]||(a[_.pa]=++_.lg)};_.mg=function(a){window.Error.captureStackTrace?window.Error.captureStackTrace(this,_.mg):this.stack=(0,window.Error)().stack||"";a&&(this.message=(0,window.String)(a))};_.ng=function(a,c){return 0<=(0,_.og)(a,c)};_.pg=function(a,c){var f=(0,_.og)(a,c),g;(g=0<=f)&&_.qg.splice.call(a,f,1);return g};_.rg=function(a){var c=a.length;if(0<c){for(var f=(0,window.Array)(c),g=0;g<c;g++)f[g]=a[g];return f}return[]}; _.sg=function(a,c,f){return 2>=arguments.length?_.qg.slice.call(a,c):_.qg.slice.call(a,c,f)};_.lg=0;(0,_.F)(_.mg,window.Error);_.mg.prototype.name="CustomError";
_.qg=window.Array.prototype;_.og=_.qg.indexOf?function(a,c,f){return _.qg.indexOf.call(a,c,f)}:function(a,c,f){f=f==_.s?0:0>f?window.Math.max(0,a.length+f):f;if((0,_.ga)(a))return!(0,_.ga)(c)||1!=c.length?-1:a.indexOf(c,f);for(;f<a.length;f++)if(f in a&&a[f]===c)return f;return-1};_.tg=_.qg.forEach?function(a,c,f){_.qg.forEach.call(a,c,f)}:function(a,c,f){for(var g=a.length,h=(0,_.ga)(a)?a.split(""):a,l=0;l<g;l++)l in h&&c.call(f,h[l],l,a)};
_.ug=_.qg.filter?function(a,c,f){return _.qg.filter.call(a,c,f)}:function(a,c,f){for(var g=a.length,h=[],l=0,n=(0,_.ga)(a)?a.split(""):a,r=0;r<g;r++)if(r in n){var u=n[r];c.call(f,u,r,a)&&(h[l++]=u)}return h};_.vg=_.qg.map?function(a,c,f){return _.qg.map.call(a,c,f)}:function(a,c,f){for(var g=a.length,h=(0,window.Array)(g),l=(0,_.ga)(a)?a.split(""):a,n=0;n<g;n++)n in l&&(h[n]=c.call(f,l[n],n,a));return h};
_.wg=_.qg.some?function(a,c,f){return _.qg.some.call(a,c,f)}:function(a,c,f){for(var g=a.length,h=(0,_.ga)(a)?a.split(""):a,l=0;l<g;l++)if(l in h&&c.call(f,h[l],l,a))return _.q;return _.t};_.xg=_.qg.every?function(a,c,f){return _.qg.every.call(a,c,f)}:function(a,c,f){for(var g=a.length,h=(0,_.ga)(a)?a.split(""):a,l=0;l<g;l++)if(l in h&&!c.call(f,h[l],l,a))return _.t;return _.q};

_.yg=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};_.zg=function(a,c){if(c)return a.replace(_.Ag,"&amp;").replace(_.Bg,"&lt;").replace(_.Cg,"&gt;").replace(_.Dg,"&quot;");if(!_.Eg.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(_.Ag,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(_.Bg,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(_.Cg,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(_.Dg,"&quot;"));return a};_.Fg=function(){return _.H.navigator?_.H.navigator.userAgent:_.s};_.Gg=function(){return _.H.navigator};
_.Hg=function(){var a=_.H.document;return a?a.documentMode:_.p};
_.Ig=function(a){var c;if(!(c=_.Jg[a])){c=0;for(var f=(0,_.yg)((0,window.String)(_.Kg)).split("."),g=(0,_.yg)((0,window.String)(a)).split("."),h=window.Math.max(f.length,g.length),l=0;0==c&&l<h;l++){var n=f[l]||"",r=g[l]||"",u=(0,window.RegExp)("(\\d*)(\\D*)","g"),w=(0,window.RegExp)("(\\d*)(\\D*)","g");do{var x=u.exec(n)||["","",""],A=w.exec(r)||["","",""];if(0==x[0].length&&0==A[0].length)break;c=((0==x[1].length?0:(0,window.parseInt)(x[1],10))<(0==A[1].length?0:(0,window.parseInt)(A[1],10))?-1:
(0==x[1].length?0:(0,window.parseInt)(x[1],10))>(0==A[1].length?0:(0,window.parseInt)(A[1],10))?1:0)||((0==x[2].length)<(0==A[2].length)?-1:(0==x[2].length)>(0==A[2].length)?1:0)||(x[2]<A[2]?-1:x[2]>A[2]?1:0)}while(0==c)}c=_.Jg[a]=0<=c}return c};_.Lg=function(a){return _.T&&_.Mg>=a};_.Eg=/[&<>\"]/;_.Dg=/\"/g;_.Cg=/>/g;_.Bg=/</g;_.Ag=/&/g;_.Rg=_.Qg=_.Pg=_.Og=_.Ng=_.t;
if(_.Tg=(0,_.Fg)()){_.Ug=(0,_.Gg)();_.Ng=0==_.Tg.indexOf("Opera");_.Og=!_.Ng&&-1!=_.Tg.indexOf("MSIE");_.Qg=(_.Pg=!_.Ng&&-1!=_.Tg.indexOf("WebKit"))&&-1!=_.Tg.indexOf("Mobile");_.Rg=!_.Ng&&!_.Pg&&"Gecko"==_.Ug.product}_.Vg=_.Ng;_.T=_.Og;_.Wg=_.Rg;_.Xg=_.Pg;_.Yg=_.Qg;_.Zg=(0,_.Gg)();_.$g=_.Zg&&_.Zg.platform||"";_.Sg=-1!=_.$g.indexOf("Mac");_.$g.indexOf("Win");_.$g.indexOf("Linux");_.ah=!!(0,_.Gg)()&&-1!=((0,_.Gg)().appVersion||"").indexOf("X11");
a:{_.ch="";if(_.Vg&&_.H.opera){_.eh=_.H.opera.version;_.ch="function"==typeof _.eh?(0,_.eh)():_.eh}else if(_.Wg?_.dh=/rv\:([^\);]+)(\)|;)/:_.T?_.dh=/MSIE\s+([^\);]+)(\)|;)/:_.Xg&&(_.dh=/WebKit\/(\S+)/),_.dh){_.fh=_.dh.exec((0,_.Fg)());_.ch=_.fh?_.fh[1]:""}if(_.T){_.gh=(0,_.Hg)();if(_.gh>(0,window.parseFloat)(_.ch)){_.bh=(0,window.String)(_.gh);break a}}_.bh=_.ch}_.Kg=_.bh;_.Jg={};_.hh=_.H.document;_.Mg=!_.hh||!_.T?_.p:(0,_.Hg)()||("CSS1Compat"==_.hh.compatMode?(0,window.parseInt)(_.Kg,10):5);

_.ih=function(a,c,f){for(var g in a)c.call(f,a[g],g,a)};_.jh=function(a){var c={},f;for(f in a)c[f]=a[f];return c};_.kh=function(a,c){for(var f,g,h=1;h<arguments.length;h++){g=arguments[h];for(f in g)a[f]=g[f];for(var l=0;l<_.lh.length;l++)f=_.lh[l],window.Object.prototype.hasOwnProperty.call(g,f)&&(a[f]=g[f])}};_.lh="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");

_.mh=function(a){a=a.className;return(0,_.ga)(a)&&a.match(/\S+/g)||[]};_.nh=function(a,c){for(var f=(0,_.mh)(a),g=(0,_.sg)(arguments,1),h=f.length+g.length,l=f,n=0;n<g.length;n++)(0,_.ng)(l,g[n])||l.push(g[n]);a.className=f.join(" ");return f.length==h};_.oh=function(a,c){var f=(0,_.mh)(a),g=(0,_.sg)(arguments,1),h,l=g;h=(0,_.ug)(f,function(a){return!(0,_.ng)(l,a)});a.className=h.join(" ");return h.length==f.length-g.length};_.ph=function(a){return(0,_.ga)(a)?window.document.getElementById(a):a};
_.qh=function(a,c,f){return(0,_.rh)(window.document,arguments)};
_.rh=function(a,c){var f=c[0],g=c[1];if(!_.sh&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',(0,_.zg)(g.name),'"');if(g.type){f.push(' type="',(0,_.zg)(g.type),'"');var h={};(0,_.kh)(h,g);delete h.type;g=h}f.push(">");f=f.join("")}var l=a.createElement(f);g&&((0,_.ga)(g)?l.className=g:(0,_.ea)(g)?_.nh.apply(_.s,[l].concat(g)):(0,_.ih)(g,function(a,c){"style"==c?l.style.cssText=a:"class"==c?l.className=a:"for"==c?l.htmlFor=a:c in _.th?l.setAttribute(_.th[c],a):0==c.lastIndexOf("aria-",0)||
0==c.lastIndexOf("data-",0)?l.setAttribute(c,a):l[c]=a}));2<c.length&&(0,_.uh)(a,l,c,2);return l};_.uh=function(a,c,f,g){function h(f){f&&c.appendChild((0,_.ga)(f)?a.createTextNode(f):f)}for(;g<f.length;g++){var l=f[g];if((0,_.fa)(l)&&!((0,_.ia)(l)&&0<l.nodeType)){var n=_.tg,r;a:{if((r=l)&&"number"==typeof r.length){if((0,_.ia)(r)){r="function"==typeof r.item||"string"==typeof r.item;break a}if((0,_.ha)(r)){r="function"==typeof r.item;break a}}r=_.t}n(r?(0,_.rg)(l):l,h)}else h(l)}};
_.vh=function(a){for(var c;c=a.firstChild;)a.removeChild(c)};_.wh=function(a,c){c.parentNode&&c.parentNode.insertBefore(a,c)};_.xh=function(a,c){c.parentNode&&c.parentNode.insertBefore(a,c.nextSibling)};_.yh=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):_.s};_.zh=function(a){var c,f=a.parentNode;if(f&&11!=f.nodeType){if(a.removeNode)return a.removeNode(_.t);for(;c=a.firstChild;)f.insertBefore(c,a);return(0,_.yh)(a)}};
_.Ah=function(a){return a.firstElementChild!=_.p?a.firstElementChild:(0,_.Bh)(a.firstChild,_.q)};_.Ch=function(a){return a.nextElementSibling!=_.p?a.nextElementSibling:(0,_.Bh)(a.nextSibling,_.q)};_.Bh=function(a,c){for(;a&&1!=a.nodeType;)a=c?a.nextSibling:a.previousSibling;return a};
_.Dh=function(a,c){if(a.contains&&1==c.nodeType)return a==c||a.contains(c);if("undefined"!=typeof a.compareDocumentPosition)return a==c||(0,window.Boolean)(a.compareDocumentPosition(c)&16);for(;c&&a!=c;)c=c.parentNode;return c==a};_.Eh=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};_.Fh=function(a,c){if("textContent"in a)a.textContent=c;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=c}else(0,_.vh)(a),a.appendChild((0,_.Eh)(a).createTextNode(c))};
_.Gh=function(a){if(_.Hh&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var c=[];(0,_.Ih)(a,c,_.q);a=c.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");_.Hh||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a};_.Jh=function(a){var c=[];(0,_.Ih)(a,c,_.t);return c.join("")};
_.Ih=function(a,c,f){if(!(a.nodeName in _.Kh))if(3==a.nodeType)f?c.push((0,window.String)(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):c.push(a.nodeValue);else if(a.nodeName in _.Lh)c.push(_.Lh[a.nodeName]);else for(a=a.firstChild;a;)(0,_.Ih)(a,c,f),a=a.nextSibling};_.Mh=function(a){this.b=a||_.H.document||window.document};
_.sh=!_.T||(0,_.Lg)(9);!_.Wg&&!_.T||_.T&&(0,_.Lg)(9)||_.Wg&&(0,_.Ig)("1.9.1");_.Hh=_.T&&!(0,_.Ig)("9");_.th={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};_.Kh={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1};_.Lh={IMG:" ",BR:"\n"};_.C=_.Mh.prototype;_.C.p=function(a){return(0,_.ga)(a)?this.b.getElementById(a):a};_.C.F=function(a,c,f){return(0,_.rh)(this.b,arguments)};_.C.createElement=function(a){return this.b.createElement(a)}; _.C.appendChild=function(a,c){a.appendChild(c)};_.C.Yk=_.wh;_.C.Rf=_.yh;_.C.Co=_.zh;_.C.Ud=_.Ah;_.C.$o=_.Ch;_.C.contains=_.Dh;

_.Nh=function(a){return"CSS1Compat"==a.compatMode};_.Oh=function(a){return!_.Xg&&(0,_.Nh)(a)?a.documentElement:a.body};_.Ph=function(a,c){this.width=a;this.height=c};_.Qh=function(a,c){this.x=(0,_.D)(a)?a:0;this.y=(0,_.D)(c)?c:0};_.Rh=function(a){var c=(0,_.Oh)(a);a=a.parentWindow||a.defaultView;return new _.Qh(a.pageXOffset||c.scrollLeft,a.pageYOffset||c.scrollTop)};_.Sh=function(a){a=a.document;a=(0,_.Nh)(a)?a.documentElement:a.body;return new _.Ph(a.clientWidth,a.clientHeight)};_.Th=function(a){return(0,_.Rh)(a.b)};
_.Uh=function(a){return a.b.parentWindow||a.b.defaultView};_.Vh=function(a){return(0,_.Nh)(a.b)};_.Wh=function(a){return(0,_.Sh)(a||window)};_.Xh=function(a){return a?new _.Mh((0,_.Eh)(a)):_.Yh||(_.Yh=new _.Mh)};_.Zh=function(a){return a?a.parentWindow||a.defaultView:window};_.$h=function(a,c){var f=(0,_.Eh)(a);return f.defaultView&&f.defaultView.getComputedStyle&&(f=f.defaultView.getComputedStyle(a,_.s))?f[c]||f.getPropertyValue(c)||"":""};
_.ai=function(a,c){return(0,_.$h)(a,c)||(a.currentStyle?a.currentStyle[c]:_.s)||a.style&&a.style[c]};_.bi=function(a){return(0,_.ai)(a,"position")};_.ci=function(a){a=a?(0,_.Eh)(a):window.document;return _.T&&!(0,_.Lg)(9)&&!(0,_.Vh)((0,_.Xh)(a))?a.body:a.documentElement};_.di=function(a){var c=a.getBoundingClientRect();_.T&&(a=a.ownerDocument,c.left-=a.documentElement.clientLeft+a.body.clientLeft,c.top-=a.documentElement.clientTop+a.body.clientTop);return c};
_.ei=function(a){if(_.T&&!(0,_.Lg)(8))return a.offsetParent;var c=(0,_.Eh)(a),f=(0,_.ai)(a,"position"),g="fixed"==f||"absolute"==f;for(a=a.parentNode;a&&a!=c;a=a.parentNode)if(f=(0,_.ai)(a,"position"),g=g&&"static"==f&&a!=c.documentElement&&a!=c.body,!g&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==f||"absolute"==f||"relative"==f))return a;return _.s};
_.fi=function(a){var c,f=(0,_.Eh)(a),g=(0,_.ai)(a,"position"),h=_.Wg&&f.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==g&&(c=f.getBoxObjectFor(a))&&(0>c.screenX||0>c.screenY),l=new _.Qh(0,0),n=(0,_.ci)(f);if(a==n)return l;if(a.getBoundingClientRect)c=(0,_.di)(a),a=(0,_.Th)((0,_.Xh)(f)),l.x=c.left+a.x,l.y=c.top+a.y;else if(f.getBoxObjectFor&&!h)c=f.getBoxObjectFor(a),a=f.getBoxObjectFor(n),l.x=c.screenX-a.screenX,l.y=c.screenY-a.screenY;else{c=a;do{l.x+=c.offsetLeft;l.y+=c.offsetTop;c!=a&&
(l.x+=c.clientLeft||0,l.y+=c.clientTop||0);if(_.Xg&&"fixed"==(0,_.bi)(c)){l.x+=f.body.scrollLeft;l.y+=f.body.scrollTop;break}c=c.offsetParent}while(c&&c!=a);if(_.Vg||_.Xg&&"absolute"==g)l.y-=f.body.offsetTop;for(c=a;(c=(0,_.ei)(c))&&c!=f.body&&c!=n;)if(l.x-=c.scrollLeft,!_.Vg||"TR"!=c.tagName)l.y-=c.scrollTop}return l};_.gi=function(a,c){var f=new _.Qh(0,0),g=(0,_.Zh)((0,_.Eh)(a)),h=a;do{var l=g==c?(0,_.fi)(h):(0,_.hi)(h);f.x+=l.x;f.y+=l.y}while(g&&g!=c&&(h=g.frameElement)&&(g=g.parent));return f};
_.hi=function(a){var c=new _.Qh;if(1==a.nodeType){if(a.getBoundingClientRect){var f=(0,_.di)(a);c.x=f.left;c.y=f.top}else{var f=(0,_.Th)((0,_.Xh)(a)),g=(0,_.fi)(a);c.x=g.x-f.x;c.y=g.y-f.y}if(_.Wg&&!(0,_.Ig)(12)){var h;_.T?h="-ms-transform":_.Xg?h="-webkit-transform":_.Vg?h="-o-transform":_.Wg&&(h="-moz-transform");var l;h&&(l=(0,_.ai)(a,h));l||(l=(0,_.ai)(a,"transform"));l?(a=l.match(_.ii),a=!a?new _.Qh(0,0):new _.Qh((0,window.parseFloat)(a[1]),(0,window.parseFloat)(a[2]))):a=new _.Qh(0,0);c=new _.Qh(c.x+
a.x,c.y+a.y)}}else h=(0,_.ha)(a.Jo),l=a,a.targetTouches?l=a.targetTouches[0]:h&&a.Oa.targetTouches&&(l=a.Oa.targetTouches[0]),c.x=l.clientX,c.y=l.clientY;return c};_.ji=function(a){if("none"!=(0,_.ai)(a,"display"))return(0,_.mi)(a);var c=a.style,f=c.display,g=c.visibility,h=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=(0,_.mi)(a);c.display=f;c.position=h;c.visibility=g;return a};
_.mi=function(a){var c=a.offsetWidth,f=a.offsetHeight,g=_.Xg&&!c&&!f;return(!(0,_.D)(c)||g)&&a.getBoundingClientRect?(a=(0,_.di)(a),new _.Ph(a.right-a.left,a.bottom-a.top)):new _.Ph(c,f)};_.ni=function(a,c){var f=a.style;"opacity"in f?f.opacity=c:"MozOpacity"in f?f.MozOpacity=c:"filter"in f&&(f.filter=""===c?"":"alpha(opacity="+100*c+")")};_.Ph.prototype.X=function(){return new _.Ph(this.width,this.height)};_.Ph.prototype.gb=function(){return!(this.width*this.height)};
_.Ph.prototype.floor=function(){this.width=window.Math.floor(this.width);this.height=window.Math.floor(this.height);return this};_.Ph.prototype.round=function(){this.width=window.Math.round(this.width);this.height=window.Math.round(this.height);return this};_.Qh.prototype.X=function(){return new _.Qh(this.x,this.y)};
_.oi=_.Wg?"MozUserSelect":_.Xg?"WebkitUserSelect":_.s;_.ii=/matrix\([0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, ([0-9\.\-]+)p?x?, ([0-9\.\-]+)p?x?\)/;
_.pi=function(a){return"rtl"==(0,_.ai)(a,"direction")};_.qi=function(a){return(0,window.String)(a).replace(/\-([a-z])/g,function(a,f){return f.toUpperCase()})};_.ri=function(a,c,f){a.style[(0,_.qi)(f)]=c};_.si=function(a,c,f,g){this.left=a;this.top=c;this.width=f;this.height=g};_.U=function(a,c){a.style.display=c?"":"none"};_.ti=function(a){var c=(0,_.fi)(a);a=(0,_.ji)(a);return new _.si(c.x,c.y,a.width,a.height)};_.ui=function(a,c,f){(0,_.ga)(c)?(0,_.ri)(a,f,c):(0,_.ih)(c,(0,_.ma)(_.ri,a))};
_.si.prototype.X=function(){return new _.si(this.left,this.top,this.width,this.height)};_.si.prototype.contains=function(a){return a instanceof _.si?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};

_.vi=function(a,c,f,g){this.top=a;this.right=c;this.bottom=f;this.left=g};
_.wi=function(a,c,f,g){a=g||a;c=c&&"*"!=c?c.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(c||f))return a.querySelectorAll(c+(f?"."+f:""));if(f&&a.getElementsByClassName){a=a.getElementsByClassName(f);if(c){g={};for(var h=0,l=0,n;n=a[l];l++)c==n.nodeName&&(g[h++]=n);g.length=h;return g}return a}a=a.getElementsByTagName(c||"*");if(f){g={};for(l=h=0;n=a[l];l++)c=n.className,"function"==typeof c.split&&(0,_.ng)(c.split(/\s+/),f)&&(g[h++]=n);g.length=h;return g}return a};
_.xi=function(a,c,f,g){if(/^\d+px?$/.test(c))return(0,window.parseInt)(c,10);var h=a.style[f],l=a.runtimeStyle[f];a.runtimeStyle[f]=a.currentStyle[f];a.style[f]=c;c=a.style[g];a.style[f]=h;a.runtimeStyle[f]=l;return c};_.yi=function(a,c){return(0,_.xi)(a,a.currentStyle?a.currentStyle[c]:_.s,"left","pixelLeft")};_.zi=function(a,c){if("none"==(a.currentStyle?a.currentStyle[c+"Style"]:_.s))return 0;var f=a.currentStyle?a.currentStyle[c+"Width"]:_.s;return f in _.Ai?_.Ai[f]:(0,_.xi)(a,f,"left","pixelLeft")};
_.Bi=function(a,c){"number"==typeof a&&(a=(c?window.Math.round(a):a)+"px");return a};_.Ci=function(a){if(_.T){var c=(0,_.zi)(a,"borderLeft"),f=(0,_.zi)(a,"borderRight"),g=(0,_.zi)(a,"borderTop");a=(0,_.zi)(a,"borderBottom");return new _.vi(g,f,a,c)}c=(0,_.$h)(a,"borderLeftWidth");f=(0,_.$h)(a,"borderRightWidth");g=(0,_.$h)(a,"borderTopWidth");a=(0,_.$h)(a,"borderBottomWidth");return new _.vi((0,window.parseFloat)(g),(0,window.parseFloat)(f),(0,window.parseFloat)(a),(0,window.parseFloat)(c))};
_.Di=function(a){var c;if(_.T){c=(0,_.yi)(a,"paddingLeft");var f=(0,_.yi)(a,"paddingRight"),g=(0,_.yi)(a,"paddingTop");a=(0,_.yi)(a,"paddingBottom");c=new _.vi(g,f,a,c)}else c=(0,_.$h)(a,"paddingLeft"),f=(0,_.$h)(a,"paddingRight"),g=(0,_.$h)(a,"paddingTop"),a=(0,_.$h)(a,"paddingBottom"),c=new _.vi((0,window.parseFloat)(g),(0,window.parseFloat)(f),(0,window.parseFloat)(a),(0,window.parseFloat)(c));return c};_.Ei=function(a,c){return new _.Qh(a.x-c.x,a.y-c.y)};
_.Fi=function(a,c){var f=(0,_.Xh)(c),g=_.s;if(_.T)f=g=f.b.createStyleSheet(),_.T?f.cssText=a:f.innerHTML=a;else{var h=(0,_.wi)(f.b,"head",_.p,_.p)[0];h||(g=(0,_.wi)(f.b,"body",_.p,_.p)[0],h=f.F("head"),g.parentNode.insertBefore(h,g));var l=g=f.F("style");_.T?l.cssText=a:l.innerHTML=a;f.appendChild(h,g)}return g};_.Gi=function(a,c,f){c instanceof _.Ph?(f=c.height,c=c.width):f==_.p&&(0,_.m)((0,window.Error)("p"));a.style.width=(0,_.Bi)(c,_.q);a.style.height=(0,_.Bi)(f,_.q)};
_.Hi=function(a){for(var c=new _.vi(0,window.Infinity,window.Infinity,0),f=(0,_.Xh)(a),g=f.b.body,h=f.b.documentElement,l=(0,_.Oh)(f.b);a=(0,_.ei)(a);)if((!_.T||0!=a.clientWidth)&&(!_.Xg||0!=a.clientHeight||a!=g)&&a!=g&&a!=h&&"visible"!=(0,_.ai)(a,"overflow")){var n=(0,_.fi)(a),r;r=a;if(_.Wg&&!(0,_.Ig)("1.9")){var u=(0,window.parseFloat)((0,_.$h)(r,"borderLeftWidth"));if((0,_.pi)(r))var w=r.offsetWidth-r.clientWidth-u-(0,window.parseFloat)((0,_.$h)(r,"borderRightWidth")),u=u+w;r=new _.Qh(u,(0,window.parseFloat)((0,_.$h)(r,
"borderTopWidth")))}else r=new _.Qh(r.clientLeft,r.clientTop);n.x+=r.x;n.y+=r.y;c.top=window.Math.max(c.top,n.y);c.right=window.Math.min(c.right,n.x+a.clientWidth);c.bottom=window.Math.min(c.bottom,n.y+a.clientHeight);c.left=window.Math.max(c.left,n.x)}g=l.scrollLeft;l=l.scrollTop;c.left=window.Math.max(c.left,g);c.top=window.Math.max(c.top,l);f=(0,_.Wh)((0,_.Uh)(f));c.right=window.Math.min(c.right,g+f.width);c.bottom=window.Math.min(c.bottom,l+f.height);return 0<=c.top&&0<=c.left&&c.bottom>c.top&&
c.right>c.left?c:_.s};_.Ii=function(a,c,f){var g,h=_.Wg&&(_.Sg||_.ah)&&(0,_.Ig)("1.9");c instanceof _.Qh?(g=c.x,c=c.y):(g=c,c=f);a.style.left=(0,_.Bi)(g,h);a.style.top=(0,_.Bi)(c,h)};_.Ji=function(a,c){return(0,_.ng)((0,_.mh)(a),c)};
_.Ki=function(a,c,f,g,h,l,n,r,u){var w,x;if(w=f.offsetParent){var A="HTML"==w.tagName||"BODY"==w.tagName;if(!A||"static"!=(0,_.bi)(w))x=(0,_.fi)(w),A||(A=(A=(0,_.pi)(w))&&_.Wg?-w.scrollLeft:A&&(!_.T||!(0,_.Ig)("8"))?w.scrollWidth-w.clientWidth-w.scrollLeft:w.scrollLeft,x=(0,_.Ei)(x,new _.Qh(A,w.scrollTop)))}w=x||new _.Qh;x=(0,_.ti)(a);if(A=(0,_.Hi)(a)){var G=new _.si(A.left,A.top,A.right-A.left,A.bottom-A.top),A=window.Math.max(x.left,G.left),J=window.Math.min(x.left+x.width,G.left+G.width);if(A<=
J){var K=window.Math.max(x.top,G.top),G=window.Math.min(x.top+x.height,G.top+G.height);K<=G&&(x.left=A,x.top=K,x.width=J-A,x.height=G-K)}}A=(0,_.Xh)(a);K=(0,_.Xh)(f);A.b!=K.b&&(J=A.b.body,K=(0,_.gi)(J,(0,_.Uh)(K)),K=(0,_.Ei)(K,(0,_.fi)(J)),_.T&&!(0,_.Vh)(A)&&(K=(0,_.Ei)(K,(0,_.Th)(A))),x.left+=K.x,x.top+=K.y);a=(c&4&&(0,_.pi)(a)?c^2:c)&-5;c=new _.Qh(a&2?x.left+x.width:x.left,a&1?x.top+x.height:x.top);c=(0,_.Ei)(c,w);h&&(c.x+=(a&2?-1:1)*h.x,c.y+=(a&1?-1:1)*h.y);var N;if(n)if(u)N=u;else if(N=(0,_.Hi)(f))N.top-=
w.y,N.right-=w.x,N.bottom-=w.y,N.left-=w.x;return(0,_.Li)(c,f,g,l,N,n,r)};
_.Li=function(a,c,f,g,h,l,n){a=a.X();var r=0,u=(f&4&&(0,_.pi)(c)?f^2:f)&-5;f=(0,_.ji)(c);n=n?n.X():f.X();if(g||0!=u)u&2?a.x-=n.width+(g?g.right:0):g&&(a.x+=g.left),u&1?a.y-=n.height+(g?g.bottom:0):g&&(a.y+=g.top);if(l){if(h){r=a;g=0;if(65==(l&65)&&(r.x<h.left||r.x>=h.right))l&=-2;if(132==(l&132)&&(r.y<h.top||r.y>=h.bottom))l&=-5;r.x<h.left&&l&1&&(r.x=h.left,g|=1);r.x<h.left&&(r.x+n.width>h.right&&l&16)&&(n.width=window.Math.max(n.width-(r.x+n.width-h.right),0),g|=4);r.x+n.width>h.right&&l&1&&(r.x=
window.Math.max(h.right-n.width,h.left),g|=1);l&2&&(g|=(r.x<h.left?16:0)|(r.x+n.width>h.right?32:0));r.y<h.top&&l&4&&(r.y=h.top,g|=2);r.y>=h.top&&(r.y+n.height>h.bottom&&l&32)&&(n.height=window.Math.max(n.height-(r.y+n.height-h.bottom),0),g|=8);r.y+n.height>h.bottom&&l&4&&(r.y=window.Math.max(h.bottom-n.height,h.top),g|=2);l&8&&(g|=(r.y<h.top?64:0)|(r.y+n.height>h.bottom?128:0));r=g}else r=256;if(r&496)return r}(0,_.Ii)(c,a);if(!(f==n||(!f||!n?0:f.width==n.width&&f.height==n.height)))h=(0,_.Vh)((0,_.Xh)((0,_.Eh)(c))),
_.T&&(!h||!(0,_.Ig)("8"))?(a=c.style,h?(h=(0,_.Di)(c),c=(0,_.Ci)(c),a.pixelWidth=n.width-c.left-h.left-h.right-c.right,a.pixelHeight=n.height-c.top-h.top-h.bottom-c.bottom):(a.pixelWidth=n.width,a.pixelHeight=n.height)):(c=c.style,_.Wg?c.MozBoxSizing="border-box":_.Xg?c.WebkitBoxSizing="border-box":c.boxSizing="border-box",c.width=window.Math.max(n.width,0)+"px",c.height=window.Math.max(n.height,0)+"px");return r};_.vi.prototype.X=function(){return new _.vi(this.top,this.right,this.bottom,this.left)}; _.vi.prototype.contains=function(a){return!this||!a?_.t:a instanceof _.vi?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom};_.Ai={thin:2,medium:4,thick:6};

_.Mi=function(){};_.Ni=function(a){a&&"function"==typeof a.K&&a.K()};_.Oi=function(a){for(var c=0,f=arguments.length;c<f;++c){var g=arguments[c];(0,_.fa)(g)?_.Oi.apply(_.s,g):(0,_.Ni)(g)}};_.Mi.prototype.ca=_.t;_.Mi.prototype.Ia=(0,_.y)("ca");_.Mi.prototype.K=function(){this.ca||(this.ca=_.q,this.B())};_.Mi.prototype.B=function(){this.Z&&_.Oi.apply(_.s,this.Z);if(this.Sb)for(;this.Sb.length;)this.Sb.shift()()};
_.Pi=function(a,c){for(var f=a.split("."),g=c||_.H,h;h=f.shift();)if(g[h]!=_.s)g=g[h];else return _.s;return g};_.Qi=function(){};_.Ri=function(a){_.Si[_.Si.length]=a;if(_.Ti)for(var c=0;c<_.Ui.length;c++)a((0,_.E)(_.Ui[c].b,_.Ui[c]))};_.Vi=function(a){_.Vi[" "](a);return a};_.Wi=function(a,c){this.type=a;this.b=this.target=c};_.Xi=function(a,c){a&&this.da(a,c)};_.Yi=function(){};
_.V=function(a,c,f,g,h){if(c){if((0,_.ea)(c)){for(var l=0;l<c.length;l++)(0,_.V)(a,c[l],f,g,h);return _.s}g=!!g;var n=_.Zi;c in n||(n[c]={U:0,xb:0});n=n[c];g in n||(n[g]={U:0,xb:0},n.U++);var n=n[g],r=(0,_.kg)(a),u;n.xb++;if(n[r]){u=n[r];for(l=0;l<u.length;l++)if(n=u[l],n.$b==f&&n.wd==h){if(n.Bd)break;return u[l].key}}else u=n[r]=[],n.U++;var w=_.$i,x=_.aj?function(a){return w.call(x.src,x.key,a)}:function(a){a=w.call(x.src,x.key,a);if(!a)return a},l=x;l.src=a;n=new _.Yi;n.da(f,l,a,c,g,h);f=n.key;
l.key=f;u.push(n);_.bj[f]=n;_.cj[r]||(_.cj[r]=[]);_.cj[r].push(n);a.addEventListener?(a==_.H||!a.Oj)&&a.addEventListener(c,l,g):a.attachEvent(c in _.dj?_.dj[c]:_.dj[c]="on"+c,l);return f}(0,_.m)((0,window.Error)("s"))};
_.ej=function(a){if(!_.bj[a])return _.t;var c=_.bj[a];if(c.Bd)return _.t;var f=c.src,g=c.type,h=c.d,l=c.capture;f.removeEventListener?(f==_.H||!f.Oj)&&f.removeEventListener(g,h,l):f.detachEvent&&f.detachEvent(g in _.dj?_.dj[g]:_.dj[g]="on"+g,h);f=(0,_.kg)(f);_.cj[f]&&(h=_.cj[f],(0,_.pg)(h,c),0==h.length&&delete _.cj[f]);c.Bd=_.q;if(c=_.Zi[g][l][f])c.kl=_.q,(0,_.fj)(g,l,f,c);delete _.bj[a];return _.q};
_.fj=function(a,c,f,g){if(!g.og&&g.kl){for(var h=0,l=0;h<g.length;h++)g[h].Bd?g[h].d.src=_.s:(h!=l&&(g[l]=g[h]),l++);g.length=l;g.kl=_.t;0==l&&(delete _.Zi[a][c][f],_.Zi[a][c].U--,0==_.Zi[a][c].U&&(delete _.Zi[a][c],_.Zi[a].U--),0==_.Zi[a].U&&delete _.Zi[a])}};_.gj=function(a,c,f){var g=_.Zi;return c in g&&(g=g[c],f in g&&(g=g[f],a=(0,_.kg)(a),g[a]))?g[a]:_.s};
_.hj=function(a,c,f,g,h){var l=1;c=(0,_.kg)(c);if(a[c]){a.xb--;a=a[c];a.og?a.og++:a.og=1;try{for(var n=a.length,r=0;r<n;r++){var u=a[r];u&&!u.Bd&&(l&=(0,_.ij)(u,h)!==_.t)}}finally{a.og--,(0,_.fj)(f,g,c,a)}}return(0,window.Boolean)(l)};_.ij=function(a,c){a.gh&&(0,_.ej)(a.key);return a.handleEvent(c)};
_.$i=function(a,c){if(!_.bj[a])return _.q;var f=_.bj[a],g=f.type,h=_.Zi;if(!(g in h))return _.q;var h=h[g],l,n;if(!_.aj){l=c||(0,_.Pi)("window.event");var r=_.q in h,u=_.t in h;if(r){if(0>l.keyCode||l.returnValue!=_.p)return _.q;a:{var w=_.t;if(0==l.keyCode)try{l.keyCode=-1;break a}catch(x){w=_.q}if(w||l.returnValue==_.p)l.returnValue=_.q}}w=new _.Xi;w.da(l,this);l=_.q;try{if(r){for(var A=[],G=w.b;G;G=G.parentNode)A.push(G);n=h[_.q];n.xb=n.U;for(var J=A.length-1;!w.zd&&0<=J&&n.xb;J--)w.b=A[J],l&= (0,_.hj)(n,A[J],g,_.q,w);if(u){n=h[_.t];n.xb=n.U;for(J=0;!w.zd&&J<A.length&&n.xb;J++)w.b=A[J],l&=(0,_.hj)(n,A[J],g,_.t,w)}}else l=(0,_.ij)(f,w)}finally{A&&(A.length=0)}return l}g=new _.Xi(c,this);return l=(0,_.ij)(f,g)};_.Si=[];_.Ui=[];_.Ti=_.t;
_.Vi[" "]=_.Qi;_.jj=!_.T||(0,_.Lg)(9);_.aj=!_.T||(0,_.Lg)(9);_.kj=_.T&&!(0,_.Ig)("9");!_.Xg||(0,_.Ig)("528");_.Wg&&(0,_.Ig)("1.9b")||_.T&&(0,_.Ig)("8")||_.Vg&&(0,_.Ig)("9.5")||_.Xg&&(0,_.Ig)("528");_.Wg&&!(0,_.Ig)("8")||_.T&&(0,_.Ig)("9");_.C=_.Wi.prototype;_.C.B=(0,_.v)();_.C.K=(0,_.v)();_.C.zd=_.t;_.C.Gg=_.q;_.C.stopPropagation=function(){this.zd=_.q};_.C.preventDefault=function(){this.Gg=_.t};(0,_.F)(_.Xi,_.Wi);_.C=_.Xi.prototype;_.C.target=_.s;_.C.Vb=_.s;_.C.jk=0;_.C.kk=0;_.C.clientX=0;_.C.clientY=0;_.C.screenX=0;_.C.screenY=0;_.C.button=0;_.C.keyCode=0;_.C.charCode=0;_.C.ctrlKey=_.t;_.C.altKey=_.t;_.C.shiftKey=_.t;_.C.metaKey=_.t;_.C.Mi=_.t;_.C.Oa=_.s;
_.C.da=function(a,c){var f=this.type=a.type;_.Wi.call(this,f);this.target=a.target||a.srcElement;this.b=c;var g=a.relatedTarget;if(g){if(_.Wg){var h;a:{try{(0,_.Vi)(g.nodeName);h=_.q;break a}catch(l){}h=_.t}h||(g=_.s)}}else"mouseover"==f?g=a.fromElement:"mouseout"==f&&(g=a.toElement);this.Vb=g;this.jk=_.Xg||a.offsetX!==_.p?a.offsetX:a.layerX;this.kk=_.Xg||a.offsetY!==_.p?a.offsetY:a.layerY;this.clientX=a.clientX!==_.p?a.clientX:a.pageX;this.clientY=a.clientY!==_.p?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==f?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Mi=_.Sg?a.metaKey:a.ctrlKey;this.state=a.state;this.Oa=a;a.defaultPrevented&&this.preventDefault();delete this.zd};_.C.stopPropagation=function(){_.Xi.u.stopPropagation.call(this);this.Oa.stopPropagation?this.Oa.stopPropagation():this.Oa.cancelBubble=_.q};
_.C.preventDefault=function(){_.Xi.u.preventDefault.call(this);var a=this.Oa;if(a.preventDefault)a.preventDefault();else if(a.returnValue=_.t,_.kj)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(c){}};_.C.Jo=(0,_.y)("Oa");_.C.B=(0,_.v)();
_.lj=0;_.C=_.Yi.prototype;_.C.key=0;_.C.Bd=_.t;_.C.gh=_.t;_.C.da=function(a,c,f,g,h,l){(0,_.ha)(a)?this.b=_.q:a&&a.handleEvent&&(0,_.ha)(a.handleEvent)?this.b=_.t:(0,_.m)((0,window.Error)("r"));this.$b=a;this.d=c;this.src=f;this.type=g;this.capture=!!h;this.wd=l;this.gh=_.t;this.key=++_.lj;this.Bd=_.t};_.C.handleEvent=function(a){return this.b?this.$b.call(this.wd||this.src,a):this.$b.handleEvent.call(this.$b,a)};
_.bj={};_.Zi={};_.cj={};_.dj={};(0,_.Ri)(function(a){_.$i=a(_.$i)});
_.mj=function(a){return"number"==typeof a};_.nj=function(a,c,f,g,h){if((0,_.ea)(c)){for(var l=0;l<c.length;l++)(0,_.nj)(a,c[l],f,g,h);return _.s}g=!!g;a=(0,_.gj)(a,c,g);if(!a)return _.t;for(l=0;l<a.length;l++)if(a[l].$b==f&&a[l].capture==g&&a[l].wd==h)return(0,_.ej)(a[l].key);return _.t};_.oj=function(a,c,f,g,h){if((0,_.ea)(c)){for(var l=0;l<c.length;l++)(0,_.oj)(a,c[l],f,g,h);return _.s}a=(0,_.V)(a,c,f,g,h);_.bj[a].gh=_.q;return a};_.pj=function(){};(0,_.F)(_.pj,_.Mi);_.C=_.pj.prototype;_.C.Oj=_.q;
_.C.xg=_.s;_.C.Yi=(0,_.ba)("xg");_.C.addEventListener=function(a,c,f,g){(0,_.V)(this,a,c,f,g)};_.C.removeEventListener=function(a,c,f,g){(0,_.nj)(this,a,c,f,g)};
_.C.dispatchEvent=function(a){var c=a.type||a,f=_.Zi;if(c in f){if((0,_.ga)(a))a=new _.Wi(a,this);else if(a instanceof _.Wi)a.target=a.target||this;else{var g=a;a=new _.Wi(c,this);(0,_.kh)(a,g)}var g=1,h,f=f[c],c=_.q in f,l;if(c){h=[];for(l=this;l;l=l.xg)h.push(l);l=f[_.q];l.xb=l.U;for(var n=h.length-1;!a.zd&&0<=n&&l.xb;n--)a.b=h[n],g&=(0,_.hj)(l,h[n],a.type,_.q,a)&&a.Gg!=_.t}if(_.t in f)if(l=f[_.t],l.xb=l.U,c)for(n=0;!a.zd&&n<h.length&&l.xb;n++)a.b=h[n],g&=(0,_.hj)(l,h[n],a.type,_.t,a)&&a.Gg!=_.t;
else for(h=this;!a.zd&&h&&l.xb;h=h.xg)a.b=h,g&=(0,_.hj)(l,h,a.type,_.t,a)&&a.Gg!=_.t;a=(0,window.Boolean)(g)}else a=_.q;return a};_.C.B=function(){_.pj.u.B.call(this);var a=_.p,c=0,f=this==_.s,g=a==_.s,a=!!a;if(f)(0,_.ih)(_.cj,function(f){for(var h=f.length-1;0<=h;h--){var l=f[h];if(g||a==l.capture)(0,_.ej)(l.key),c++}});else if(f=(0,_.kg)(this),_.cj[f])for(var f=_.cj[f],h=f.length-1;0<=h;h--){var l=f[h];if(g||a==l.capture)(0,_.ej)(l.key),c++}this.xg=_.s};

_.qj=function(a){return new _.vi(a.top,a.left+a.width,a.top+a.height,a.left)};_.rj=function(a){this.v=a;this.b=a.ma};
_.sj=function(a){var c=a.v.xa;if(a.b.anchorBox&&c&&c.ba())c=(0,_.fi)(c.ba()),a.b.anchorBox.left+=c.x,a.b.anchorBox.top+=c.y;else{c=a.b.anchor;if("_default"!=c&&"_iframe"!=c){var f=(0,_.ph)(c);if(f)a.b.anchorBox=(0,_.ti)(f);else{(0,_.ib)("Anchor not found in DOM: "+c+'. Falling back to "_default".');a.b.anchor="_default";return}}"_iframe"==c&&(c=(0,_.Wh)(),a.b.anchorBox=new _.si(0,0,c.width,c.height))}a.b.anchor=""};_.tj=function(a){_.rj.call(this,a)};
_.uj=function(a){if(a.k)return a.k;var c=a.b;!c.anchorBox&&c.anchor&&(0,_.sj)(a);var f=a.v.xa;if("_default"==c.anchor&&f){var g=(0,_.ti)((0,_.ph)(f.S));c.anchorBox=g}if(!c.anchorBox)return(0,_.ib)("No anchor box defined."),_.s;g=new _.Qh(c.anchorBox.left,c.anchorBox.top);f&&(f=(0,_.gi)(f.ba(),window),a.C=new _.Qh,a.C.x=f.x,a.C.y=f.y,g.x+=f.x,g.y+=f.y,(0,_.vj)(window,g));c={position:"absolute",background:"transparent",left:g.x+"px",top:g.y+"px",width:c.anchorBox.width+"px",height:c.anchorBox.height+
"px",zIndex:-1E4};a.k=window.document.createElement("ins");(0,_.ui)(a.k,c);window.document.body.appendChild(a.k);return a.k};
_.wj=function(a,c){var f=0,g=0;if(c.pageX||c.pageY)f=c.pageX,g=c.pageY;else if(c.clientX||c.clientY){var g=c.target?c.target:c.srcElement,f=g.ownerDocument&&g.ownerDocument.parentWindow?g.ownerDocument.parentWindow:window,h=0,g=0;_.T?(h=f.document.documentElement.scrollLeft,g=f.document.documentElement.scrollTop):(h=f.pageXOffset,g=f.pageYOffset);f=c.clientX+h;g=c.clientY+g}g=new _.Qh(f,g);return(f=(0,_.qj)((0,_.ti)(a)))&&f.contains(g)};
_.vj=function(a,c){var f=window.document.body,g=(0,_.fi)(f),f=f.currentStyle||a.getComputedStyle(f,"");f.position&&"static"!=f.position&&(c.x-=g.x,c.y-=g.y)};_.xj=function(a){var c=a.v.xa&&a.v.xa.S,c=c&&c.style.zIndex?(0,window.parseInt)(c.style.zIndex,10)+1:0;return window.Math.min(2147483647,window.Math.max(2E9,a.b.zIndex||c))};
_.yj=function(a,c,f,g,h){h=h||{x:0,y:0};if(_.zj[c]){var l=(0,_.ji)(a).width/2;h.x="top-right"==g||"bottom-right"==g?h.x+l:h.x-l}_.zj[g]&&(l=(0,_.ji)(f).width/2,h.x+=l);_.Aj[c]&&(l=(0,_.ji)(a).height/2,h.y="right-bottom"==g||"left-bottom"==g?h.y+l:h.y-l);_.Aj[g]&&(h.y+=(0,_.ji)(f).height/2);(0,_.Ki)(f,_.Bj[g],a,_.Bj[c],new _.Qh(h.x,h.y));a:{c=a;c=c.parentNode;for(f=0;c;){g=c==window.document?_.t:(g=(0,_.bi)(c))&&"static"!=g;if(g){g=c;break a}c=c.parentNode;f++}g=_.s}f=c=0;g&&(f=(0,_.fi)(g),c=-f.x,
f=-f.y);a=a.style;(0,window.parseInt)(a.left,10)<c&&(a.left=c+"px");(0,window.parseInt)(a.top,10)<f&&(a.top=f+"px")};_.Cj=function(a){_.rj.call(this,a.v);this.d=a;this.i=_.s};_.Dj=function(){this.b=[]};if("undefined"===typeof _.Ej)_.Ej={};_.rj.prototype.Z=function(){(0,_.sj)(this)};_.rj.prototype.onBeforeParentOpen=_.rj.prototype.Z;
(0,_.F)(_.tj,_.rj);_.tj.prototype.open=function(){var a=this.b,c=window.document.createElement("ins");window.document.getElementById(a.container).appendChild(c);c.style.display="block";(0,_.ui)(c,a.containerCss);this.v.Hc(c);this.v.Ka(c)};_.tj.prototype.eb=function(){window.document.getElementById(this.v.id).style.height=this.v.height+"px"};_.tj.prototype.close=function(){(0,_.yh)(this.v.S);(0,_.yh)(this.k);this.k=_.s};
_.Bj={"bottom-center":1,"bottom-end":7,"bottom-left":1,"bottom-right":3,"bottom-start":5,"left-bottom":1,"left-center":0,"left-top":0,"right-bottom":3,"right-center":2,"right-top":2,"top-center":0,"top-end":6,"top-left":0,"top-right":2,"top-start":4};_.zj={"bottom-center":_.q,"top-center":_.q};_.Aj={"left-center":_.q,"right-center":_.q};
(0,_.F)(_.Cj,_.tj);_.Cj.prototype.Z=function(){this.d.Z()};_.Cj.prototype.onBeforeParentOpen=_.Cj.prototype.Z;_.Cj.prototype.open=function(){this.d.open();if(this.b.closeClickDetection||this.b.hideClickDetection)this.i=(0,_.V)(window.document,"click",(0,_.E)(this.j,this),_.t)};_.Cj.prototype.open=_.Cj.prototype.open;_.Cj.prototype.eb=function(a){this.d.eb(a)};_.Cj.prototype.onready=_.Cj.prototype.eb;_.Cj.prototype.vl=function(a){this.d.onRenderStart&&this.d.onRenderStart(a)};
_.Cj.prototype.onRenderStart=_.Cj.prototype.vl;_.Cj.prototype.close=function(){if(this.b.closeClickDetection||this.b.hideClickDetection)(0,_.ej)(this.i),this.i=_.s;this.d.close()};_.Cj.prototype.close=_.Cj.prototype.close;_.Cj.prototype.j=function(a){(0,_.wj)(this.v.S,a)||(this.b.hideClickDetection&&this.v.show?this.v.show(_.t):this.v.close())};
(0,_.F)(_.Dj,_.pj);_.Dj.prototype.B=function(){for(var a in this.b)(0,_.ej)(a);this.b=[];this.d=_.H.clearTimeout(this.d);_.Dj.u.B.call(this);this.dispatchEvent({type:"dispose"})};(0,_.L)("iframes.styles.createAnchor",function(){return new _.Dj(["email","oid","o","cid"])},_.p);

_.Fj=function(a){var c=a.v.xa;if(!c||!a.C)return _.t;var f=a.b,f=new _.Qh(f.anchorBox.left,f.anchorBox.top),c=(0,_.gi)(c.ba(),window);if(c.x==a.C.x&&c.y==a.C.y)return _.t;a.C.x=c.x;a.C.y=c.y;f.x+=c.x;f.y+=c.y;(0,_.vj)(window,f);(0,_.ui)(a.k,{left:f.x+"px",top:f.y+"px"});return _.q};_.Gj=function(a,c,f,g){if(a!=_.s)for(a=a.firstChild;a;){if(c(a)&&(f.push(a),g)||(0,_.Gj)(a,c,f,g))return _.q;a=a.nextSibling}return _.t};_.Hj=function(a,c){for(var f in a)if(a[f]==c)return _.q;return _.t};
_.Ij=function(a,c){var f=c||window.document,g=_.s;f.querySelectorAll&&f.querySelector?f=f.querySelector("."+a):(f=c||window.document,f=(f.querySelectorAll&&f.querySelector?f.querySelectorAll("."+a):f.getElementsByClassName?f.getElementsByClassName(a):(0,_.wi)(window.document,"*",a,c))[0]);return(g=f)||_.s};_.Jj=function(a){_.rj.call(this,a)};_.Kj=function(a,c){var f=[];return(0,_.Gj)(a,function(a){return(0,_.Ji)(a,c)},f,_.q)?f[0]:_.p};
_.Lj=function(a,c,f,g,h,l,n){return['<img class="',h?h+" ":"",n?'"':'gc-reset"',' width="',c,'" height="',f,'" src="',l?"":"https://ssl.gstatic.com/s2/oz/images/stars/po/bubblev1/",g,'"/>'].join("")};_.Mj=function(a){a.Be||(a.Be=window.setInterval((0,_.E)(a.zo,a),1E3))};_.Nj=function(a){a.Be&&(window.clearInterval(a.Be),a.Be=_.s)};_.Oj=function(a,c){var f=(c||{}).height;f&&(a.v.maxExpectedSize||(a.v.maxExpectedSize={}),a.v.maxExpectedSize.height=f)};
_.Pj=function(a,c){a.Vk=_.q;var f=c||{},g=f.height;g&&(a.v.height=g);var h=f.width;h&&(a.v.width=h);h=f.contentWidth||h;+h&&(a.v.contentWidth=h);g=f.contentHeight||g;+g&&(a.v.contentHeight=g);(0,_.Oj)(a,f.maxExpectedSize);a.ka&&(0,_.Qj)(a,_.t);a.Ba||a.show(_.q)};_.Qj=function(a,c){a.mf=c;var f=(0,_.Ij)("pls-spinner",a.v.S);f&&(f.style.visibility=c?"":"hidden");if(f=(0,_.Ij)("goog-bubble-content",a.v.S))f.style.visibility=c?"hidden":""}; _.Rj=function(a){var c=a.b.bubbleGroup||"",f=_.Sj[c];f!==a.v&&(f&&(f.ma.hideClickDetection&&f.show?f.show(_.t):f.close()),_.Sj[c]=a.v)};_.Tj=function(a){var c=window.Math.max((0,_.xj)(a),_.Uj+1);(0,_.ui)(a.v.S,{zIndex:c});_.Uj=c};
try{(0,_.Fi)(".gc-bubbleDefault{text-align:left;padding:0 !important;margin:0 !important;border:0 !important;table-layout:auto !important}.gc-reset{border:0 !important;padding:0 !important;margin:0 !important;text-align:left}.pls-bubbleTop{border-bottom:1px solid #ccc !important}.pls-topTail,.pls-vertShimLeft,.pls-contentLeft{background-image:url(//ssl.gstatic.com/s2/oz/images/stars/po/bubblev1/border_3.gif) !important}.pls-topTail{background-repeat:repeat-x !important;background-position:bottom !important}.pls-vertShim{background-color:#fff !important;text-align:right}.pls-vertShimLeft{background-repeat:repeat-y !important;background-position:right !important;height:4px}.pls-vertShimRight{height:4px}.pls-confirm-container .pls-vertShim{background-color:#fff3c2 !important}.pls-contentWrap{background-color:#fff !important;position:relative !important;vertical-align:top}.pls-contentLeft{background-repeat:repeat-y;background-position:right;vertical-align:top}.pls-dropRight{background-image:url(//ssl.gstatic.com/s2/oz/images/stars/po/bubblev1/bubbleDropR_3.png) !important;background-repeat:repeat-y !important;vertical-align:top}.pls-vert,.pls-tailleft,.pls-dropTR .pls-dropBR,.pls-dropBL,.pls-vert img{vertical-align:top}.pls-dropBottom{background-image:url(//ssl.gstatic.com/s2/oz/images/stars/po/bubblev1/bubbleDropB_3.png) !important;background-repeat:repeat-x !important;width:100%;vertical-align:top}.pls-topLeft{background:inherit !important;text-align:right;vertical-align:bottom}.pls-topRight{background:inherit !important;text-align:left;vertical-align:bottom}.pls-bottomLeft{background:inherit !important;text-align:right}.pls-bottomRight{background:inherit !important;text-align:left;vertical-align:top}.pls-tailtop,.pls-tailright,.pls-tailbottom,.pls-tailleft{display:none;position:relative}.pls-tailbottom,.pls-tailtop,.pls-tailright,.pls-tailleft,.pls-dropTR,.pls-dropBR,.pls-dropBL{background-image:url(//ssl.gstatic.com/s2/oz/images/stars/po/bubblev1/bubbleSprite_3.png) !important;background-repeat:no-repeat}.pls-tailbottom{background-position:-23px 0}.pls-confirm-container .pls-tailbottom{background-position:-23px -10px}.pls-tailtop{background-position:-19px -20px}.pls-tailright{background-position:0 0}.pls-tailleft{background-position:-10px 0}.pls-tailtop{vertical-align:top}.gc-bubbleDefault td{line-height:0;font-size:0}.pls-topLeft img,.pls-topRight img,.pls-tailbottom{vertical-align:bottom}.pls-bottomLeft img,.bubbleDropTR,.pls-dropBottomL img,.pls-dropBottom img,.pls-dropBottomR img,.pls-bottomLeft{vertical-align:top}.pls-dropTR{background-position:0 -22px}.pls-dropBR{background-position:0 -27px}.pls-dropBL{background-position:0 -16px}.pls-spacertop,.pls-spacerright,.pls-spacerbottom,.pls-spacerleft{position:static !important}.pls-spinner{bottom:0;position:absolute;left:0;margin:auto;right:0;top:0}")}catch(Vj){(0,_.ib)("Failed to install bubble styles: "+
Vj),_.H.setTimeout((0,_.v)(),0)}(0,_.F)(_.Jj,_.tj);_.C=_.Jj.prototype;_.C.Tk=_.t;_.C.Vk=_.t;_.C.mf=_.t;_.C.Ai=_.t;_.C.Be=_.s;_.C.zj=_.t;_.Sj={};_.Uj=0;_.Wj={Dm:"bottom",an:"left",Fn:"right",Kn:"top"};_.Xj={top:"bottom",bottom:"top",left:"right",right:"left"};_.Yj={Gm:"center",an:"left",Fn:"right"};_.Zj={Dm:"bottom",Gm:"center",Kn:"top"};_.$j={"pls-default":"pls-container","pls-confirm":"pls-confirm-container"};_.C=_.Jj.prototype;
_.C.Xc=function(a){+a.width&&(this.v.width=a.width);+a.height&&(this.v.height=a.height);+a.contentWidth&&(this.v.contentWidth=a.contentWidth);+a.contentHeight?this.v.contentHeight=a.contentHeight:+a.height&&(this.v.contentHeight=a.height);this.position(_.t,a.noreposition);return _.q};_.C.close=function(){(0,_.Nj)(this);_.Jj.u.close.call(this)};
_.C.open=function(){(0,_.Rj)(this);var a=this.v;a.ga("resize",(0,_.E)(this.Xc,this));var c=window.document.createElement("div");a.Ha("setBubbleType",(0,_.E)(this.Uk,this));a.Ha("show",(0,_.E)(this.show,this));a.Ha("showSpinner",(0,_.E)(this.Dr,this));a.Ta.closeOrHideThisBubble=(0,_.E)(this.po,this);var f=(0,window.Number)(this.b.width)||100,g=f+2+4,h={visibility:"hidden",position:"absolute",width:g+"px",left:"-1000px",top:"-1000px"};this.b.height&&(h.height=+this.b.height+2+"px");(0,_.ui)(c,h);(0,_.Oj)(this,
this.b.maxExpectedSize);this.mf=!!this.b.showSpinner;this.Ai=!!this.b.noPadding;this.zj=!!this.b.anchorToOpener;var g=(g=(0,window.String)(g))?g+"px":"100%",h=this.mf,l=this.Ai,n="";h&&(n=(0,_.Lj)(this,(0,_.M)("iframes/bubble/spinnerwidth")||16,(0,_.M)("iframes/bubble/spinnerheight")||16,(0,_.M)("iframes/bubble/spinnerurl")||"https://ssl.gstatic.com/docs/documents/share/images/spinner-1.gif","pls-spinner",_.q,_.q));n+='<div class="goog-bubble-content gc-reset"'+(h?' style="visibility:hidden;"':"")+
"></div>";c.innerHTML=['<table cellpadding="0" cellspacing="0" dir="ltr" style="width:',g,';" frame="void" rules="none" class="gc-bubbleDefault pls-container"><tr class="gc-reset"><td class="pls-topLeft gc-reset">',(0,_.Lj)(this,1,1,"border_3.gif"),'</td><td class="pls-topTail gc-reset">',(0,_.Lj)(this,15,9,"spacer.gif","pls-tailbottom"),(0,_.Lj)(this,1,1,"spacer.gif","pls-spacerbottom"),'</td><td class="pls-topRight gc-reset">',(0,_.Lj)(this,1,1,"border_3.gif"),'</td></tr><tr class="gc-reset"><td class="pls-vertShimLeft gc-reset">',
(0,_.Lj)(this,1,4,"spacer.gif"),"</td>",l?'<td rowspan="2" class="pls-contentWrap gc-reset">'+n+"</td>":'<td class="pls-vertShim gc-reset">'+(0,_.Lj)(this,1,4,"spacer.gif")+"</td>",'<td class="pls-vertShimRight gc-reset">',(0,_.Lj)(this,5,4,"spacer.gif","pls-dropTR"),'</td></tr><tr class="gc-reset"><td class="pls-contentLeft gc-reset">',(0,_.Lj)(this,9,15,"spacer.gif","pls-tailright"),(0,_.Lj)(this,1,1,"spacer.gif","pls-spacerright"),"</td>",l?"":'<td class="pls-contentWrap gc-reset">'+n+"</td>",
'<td class="pls-dropRight gc-reset">',(0,_.Lj)(this,12,19,"spacer.gif","pls-tailleft"),(0,_.Lj)(this,1,1,"spacer.gif","pls-spacerleft"),'</td></tr><tr class="gc-reset"><td class="pls-bottomLeft gc-reset">',(0,_.Lj)(this,1,1,"border_3.gif"),'</td><td class="gc-reset"><table cellpadding="0" cellspacing="0" style="width:100%" class="gc-reset"><tr class="gc-reset"><td class="pls-vert gc-reset">',(0,_.Lj)(this,4,5,"spacer.gif","pls-dropBL"),'</td><td class="pls-dropBottom gc-reset">',(0,_.Lj)(this,19,
13,"spacer.gif","pls-tailtop"),(0,_.Lj)(this,1,1,"spacer.gif","pls-spacertop"),'</td></tr></table></td><td class="pls-vert gc-reset">',(0,_.Lj)(this,5,5,"spacer.gif","pls-dropBR"),"</td></tr></table>"].join("");this.zj?(g=a.xa.S,g.style.position="relative"):g=window.document.body;g.appendChild(c);this.o=c.firstChild;this.b.bubbleType&&this.Uk(this.b.bubbleType);this.G=(0,_.Kj)(this.o,"goog-bubble-content");(g=a.S)?this.G.appendChild(g):(window.document.all&&"CSS1Compat"!=window.document.compatMode&&
(a.ld().quirkie=_.q),a.Ka(this.G||_.s,{style:"margin:0px;position:absolute;z-index:1;border-style:none;outline:none;width:"+f+"px;"}));a.Hc(c);this.mf&&(this.position(_.t),this.ka=_.q);this.b.startVisible&&(c.style.visibility="visible",(0,_.Mj)(this),(0,_.Tj)(this))};
_.C.zo=function(){var a=this.v.xa;if(!a||!this.k)(0,_.Nj)(this);else{var a=a.S,c=a.currentStyle||window.getComputedStyle(a,"");0===a.offsetWidth&&0===a.offsetHeight||"none"==c.display||"hidden"==c.visibility?this.v.close():(0,_.Fj)(this)&&this.position(_.q)}};_.C.eb=function(a){(0,_.Pj)(this,a)};_.C.vl=function(a){this.Va||(0,_.Pj)(this,a)};_.C.Dr=function(a){a&&(this.ka=_.t,this.Va=_.q);(0,_.Qj)(this,a)};
_.C.position=function(a,c){var f=this.v.Y(),g=(0,_.ph)(f);if(g){g.style.height=(this.v.contentHeight||+this.b.contentHeight||this.v.height||+this.b.height)+"px";f=this.v.contentWidth||+this.b.contentWidth||+this.b.width;g.style.width=f?f+"px":"100%";f=this.v.width||+this.b.width;g=this.v.height||+this.b.height;(0,_.ui)(this.G,{width:f+"px",height:g+"px"});var h=f+2+4,l=(this.Ai?window.Math.max(g,4):g+4)+2+4;this.o.style.width=h+"px";g=this.v.S;g.style.width=h+"px";var f=(0,_.uj)(this),n=(0,_.hi)(f),
r=(0,_.ti)(g),u=(0,_.ti)(f),w=(0,_.Wh)(window);if(!this.Tk||a){this.Tk=_.q;var x=this.v.maxExpectedSize,r=r.X();x&&x.height&&(r.height=x.height);a:{var A=this.b.expandTo,x=["bottom","top","right","left"];if(A){for(var A=x=A.concat(x),G={},J=0,K=0;K<A.length;){var N=A[K++];G[N]||(G[N]=_.q,A[J++]=N)}A.length=J}for(A=0;A<x.length;++A)switch(x[A]){case "bottom":if(n.y+u.height+r.height<=w.height){r="bottom";break a}break;case "top":if(0<=n.y-r.height){r="top";break a}break;case "left":if(0<=n.x-r.width){r=
"left";break a}break;case "right":if(n.x+r.width+u.width<=w.width){r="right";break a}}r=x[0]}this.d=r;this.i=this.b.anchorPosition;this.j=this.b.targetPosition;if("top"==this.d||"bottom"==this.d){if(!(0,_.Hj)(_.Yj,this.i)||!(0,_.Hj)(_.Yj,this.j))this.j=this.i="left"}else if(!(0,_.Hj)(_.Zj,this.i)||!(0,_.Hj)(_.Zj,this.j))this.j=this.i="center";(this.z=this.b.arrowPosition)?"top"==this.d||"bottom"==this.d?(0,_.Hj)(_.Yj,this.z)||(this.z="center"):(0,_.Hj)(_.Zj,this.z)||(this.z="center"):this.z="center";
r=this.d;x=this.j;A={};A.anchor=r+"-"+this.i;A.target=_.Xj[r]+"-"+x;this.ea=A;(0,_.Kj)(this.o,"pls-spacer"+this.d).style.display="none";for(var da in _.Wj)_.Wj.hasOwnProperty(da)&&(r=_.Wj[da],r!=this.d&&((0,_.Kj)(this.o,"pls-spacer"+r).style.display="block",(0,_.Kj)(this.o,"pls-tail"+r).style.display="none"));this.ca=(0,_.Kj)(this.o,"pls-tail"+this.d);this.ca.style.display="inline"}switch(this.d){case "top":l+=8;break;case "right":h+=8;break;case "bottom":l+=8;break;case "left":h+=7}(0,_.ui)(this.o,
{width:h+"px",height:l+"px"});(0,_.ui)(g,{width:h+"px",height:l+"px"});h=r=(0,_.ti)(g);da={x:0,y:0};x=h.width;A=h.height;"top"==this.d||"bottom"==this.d?(l="right"==this.i?u.width:"center"==this.i?u.width/2:0,r="right"==this.j?x:"center"==this.j?x/2:0,n=window.Math.max(0,window.Math.min(n.x,w.width-l)),n+=l-r,"right"==this.j&&(da.x+=4),n+x>w.width&&(w=n+x-w.width,da.x-=w,n-=w),0>n&&(da.x-=n)):(l="bottom"==this.i?u.height:"center"==this.i?u.height/2:0,r="bottom"==this.j?A:"center"==this.j?A/2:0,n=
window.Math.max(0,window.Math.min(n.y,w.height-l)),n+=l-r,n+A>w.height&&(w=n+A-w.height,da.y-=w,n-=w),0>n&&(da.y-=n));w={x:-da.x,y:-da.y};"right"==this.i?da.x*=-1:"bottom"==this.i&&(da.y*=-1);l=h.width-4;r=h.height-4;n={x:0,y:0};if("top"==this.d||"bottom"==this.d){switch(this.z){case "left":n.x-=7;break;case "right":n.x=u.width-7;break;default:n.x=u.width/2-7}"center"==this.j?n.x+=l/2:"right"==this.j&&(n.x+=l);"center"==this.i?n.x-=u.width/2:"right"==this.i&&(n.x-=u.width);"top"==this.d&&(n.x-=4)}else{switch(this.z){case "top":n.y-=
7;break;case "bottom":n.y+=u.height-7;break;default:n.y+=u.height/2-7}"center"==this.j?n.y+=r/2:"bottom"==this.j&&(n.y+=r);"center"==this.i?n.y-=u.height/2:"bottom"==this.i&&(n.y-=u.height);n.y-=4}l=this.d;u=h.width;"right"==l||"left"==l?u=0:(l=window.Math.max(6,w.x+n.x),u=window.Math.min(l,u-6-15-8));l=this.d;"top"==l||"bottom"==l?w=0:(h=h.height-6-15-8,w=window.Math.min(window.Math.max(6,w.y+n.y),h));u={ao:da,Cj:{x:u,y:w}};w=(0,_.ti)(this.ca);n=(0,_.ti)(this.G);w=w.top+w.height>n.top+n.height;if(!c||
"top"===this.d||w)(0,_.ui)(this.ca,{left:u.Cj.x+"px",top:u.Cj.y+"px"}),f&&(0,_.yj)(g,this.ea.target,f,this.ea.anchor,u.ao)}else(0,_.rb)("Cannot resize already-closed iframe "+f+".")};_.C.Uk=function(a){this.o&&a in _.$j&&(this.o.className="gc-bubbleDefault "+_.$j[a])};
_.C.show=function(a){if(a&&!this.Vk&&!this.mf)this.Ba=_.t;else{var c=this.v.S.style;a?((0,_.Rj)(this),(0,_.Fj)(this),this.position(_.q),(0,_.Tj)(this)):(c.left="-10000px",c.top="-10000px");this.Ba=!a;c.visibility=a?"visible":"hidden";a?(0,_.Mj)(this):(0,_.Nj)(this);(c=this.v.Ta.onVisibilityChanged)&&c(a)}};_.C.po=function(){this.b.hideClickDetection?this.show(_.t):this.v.close()};_.S.ja("bubble",function(a){return new _.Cj(new _.Jj(a))});

});

// Copyright 2002-2012 Google Inc.
